## This demo is to get the data with following parameters:
## 各室内机对应温度
+ Database: moserver
+ Measurement: modata
+ Field: roomTemp
+ Tag: nid = 'vrf/vrf_0000CC311178CCM26232341000271K0V/indoor/0'
+ Timestemp range: between '2022-11-29 00:00:00' and '2022-11-30 00:00:00'
+ Whether it is a forecast data type: False

In [1]:
import pandas as pd
from Influxdb_API import ClientInfluxdb

In [2]:
db_name='moserver'
params={
    'measurement_name':'modata',
    'start_time':pd.to_datetime('2022-11-29 00:00:00'),
    'end_time':pd.to_datetime('2022-11-30 00:00:00'),
    'field_list':['roomTemp'],
    'tag_dict':{'nid': 'vrf/vrf_0000CC311178CCM26232341000271K0V/indoor/0'},
    'fore':False,
    'fore_horizon':None,
    'interval':None
}

In [3]:
db_client = ClientInfluxdb(db_name=db_name) # connect the database

In [4]:
df = db_client.read_influxdb(**params)

In [5]:
df

                    roomTemp
2022-11-29 00:01:20     29.7
2022-11-29 00:01:32     29.7
2022-11-29 00:04:19     29.7
2022-11-29 00:06:33     29.7
2022-11-29 00:07:19     29.7
...                      ...
2022-11-29 23:51:31     30.2
2022-11-29 23:53:45     30.2
2022-11-29 23:54:32     30.2
2022-11-29 23:57:32     30.2
2022-11-29 23:58:45     30.2

[807 rows x 1 columns]

## 各室内机运行状态
+ Database: moserver
+ Measurement: modata
+ Field: exv1Opening
+ Tag: nid = 'vrf/vrf_0000CC311178CCM26232341000271K0V/indoor/0'
+ Timestemp range: between '2022-11-29 00:00:00' and '2022-11-30 00:00:00'
+ Whether it is a forecast data type: False

In [6]:
db_name = 'moserver'
params = {
    'measurement_name': 'modata',
    'start_time': pd.to_datetime('2022-11-29 00:00:00'),
    'end_time': pd.to_datetime('2022-11-30 00:00:00'),
    'field_list': ['exv1Opening'],
    'tag_dict': {'nid': 'vrf/vrf_0000CC311178CCM26232341000271K0V/indoor/0'},
    'fore': False,
    'fore_horizon': None,
    'interval': None
}
db_client = ClientInfluxdb(db_name=db_name)  # connect the database
df = db_client.read_influxdb(**params)
df

                    exv1Opening
2022-11-29 00:01:20           0
2022-11-29 00:01:32           0
2022-11-29 00:04:19           0
2022-11-29 00:06:33           0
2022-11-29 00:07:19           0
...                         ...
2022-11-29 23:51:31           0
2022-11-29 23:53:45           0
2022-11-29 23:54:32           0
2022-11-29 23:57:32           0
2022-11-29 23:58:45           0

[807 rows x 1 columns]

## 多联机用电数据
+ Database: moserveribms
+ Measurement: ibmsV2modata
+ Field:E
+ Tag: nid = 'ibmsv2/ibmsv2_5929149262402256896/EMeter/mDev_EMeter_Roof_MDV_10'
+ Timestemp range: between '2022-11-29 00:00:00' and '2022-11-30 00:00:00'
+ Whether it is a forecast data type: False

In [7]:
db_name = 'moserveribms'
params = {
    'measurement_name': 'ibmsV2modata',
    'start_time': pd.to_datetime('2022-11-29 00:00:00'),
    'end_time': pd.to_datetime('2022-11-30 00:00:00'),
    'field_list': ['E'],
    'tag_dict': {'nid': 'ibmsv2/ibmsv2_5929149262402256896/EMeter/mDev_EMeter_Roof_MDV_10'},
    'fore': False,
    'fore_horizon': None,
    'interval': None
}
db_client = ClientInfluxdb(db_name=db_name)  # connect the database
df = db_client.read_influxdb(**params)
df

                           E
2022-11-29 00:03:28  3245.69
2022-11-29 00:12:52  3245.69
2022-11-29 00:18:28  3245.69
2022-11-29 00:27:53  3245.69
2022-11-29 00:33:29  3245.69
...                      ...
2022-11-29 23:21:15  3246.15
2022-11-29 23:35:51  3246.15
2022-11-29 23:36:17  3246.15
2022-11-29 23:50:52  3246.15
2022-11-29 23:51:18  3246.15

[193 rows x 1 columns]